services:
  user-service:
    build: ./user-service
    ports:
      - "5001:5001"

  product-service:
    build: ./product-service
    ports:
      - "5002:5002"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
